### ISSUE TITLE
Adding exe icon

### ISSUE THREAD

**Issue by BRM845** [calebhearth/steam-swtor#1]
I have followed the instructions from both here and the Muyami steam post and got everything working great.  I was hoping to change the icon of the exe file to match the swtor launcher, but am not having any luck.  

I downloaded resource hacker and can pull the exe file up, but it doesn't have the icon or icon group part need to change the icon.  I am not a programmer and know it is a matter of adding those groups (I think) but not sure how to do it.  

Any help if you can would be much appreciated.  

I assume using his code and your code for the exe produces the same result just yours is cleaned up.

Thanks in advance for any help.  

BRM

**Comment by calebhearth** [comment]
@BRM845, my code should do the same as the code in the forum.  It doesn't seem to work for me, but that seems to be a factor of my stack more than the code's ability to launch things right.

Since you're running this through Steam, the solution to your icon problem can also be fixed there.  There should be a field in the shortcut you create in your Steam library (right click and select setting, preferences, or the like &ndash; I'm not near my gaming computer presently).  In the settings window that comes up, I believe that there is a Icon field.  Click browse there and navigate to the launcher.exe in the TOR program folder, which has the icon you're looking for.  Select that and the shortcut should have the correct icon.

Just out of curiosity, what stack are you using?  Windows version, service pack, .NET version if you know it.  I'd like to get this working for myself, and knowing what makes it work for others might help.

**Comment by BRM845** [comment]
I will try my best to give you helpful info for trying to isolate why I might be working and other people are not.  

In terms of setup I simply followed the cut/paste instructions per your directions.  

I am running Win 7 Ultimate 64-bit, SP1, .NET I looked in programs/features and have .NET 4 client profile listed, but if there is another way to confirm if I have other versions I can most certainly check that too.  

I knew those icon steps and call me a dork I would be fine with that if it didn't put the shortcut arrow on the icon you point to in steam.  I can ultimately deal with it if that is the way it has to be though.  But I just wanted to try and have an icon with no shortcut arrow on it.  

Like I said anything else I can do to assist just let me know.
